Q1. Create the first numpy array of 1-D with values (1,2,3,0).
Create a second numpy array of 1-D with values (4,1,0, 6). Perform following simple arithmetic operations on these two numpy arrays:
• Addition
• Subtraction
• Multiplication
• Division

In [1]:
import numpy as np

In [ ]:
arr1=np.array([1,2,3,0])
arr2=np.array([4,1,0,6])

In [ ]:
print("The addition of Array 1 and Array 2 is",arr1+arr2)
print("The Subtraction of Array 1 and Array 2 is",arr1-arr2)
print("The Multiplication of Array 1 and Array 2 is",arr1*arr2)
print("The Division of Array 1 and Array 2 is",arr1/arr2)

Q2. Create the first numpy array of random integers between 1-100 of 5 elements in 1-D. Create second numpy array of 2-D for the same range of integers of shape 4*5. Now perform following simple arithmetic operations on these two numpy arrays:
• Addition
• Subtraction

In [ ]:
arr1_1d=np.random.randint(1,101,5)
arr1_2d=np.random.randint(1,101,(4,5))

In [ ]:
np.add(arr1_1d,arr1_2d)

In [ ]:
np.subtract(arr1_1d,arr1_2d)

Q3. Create a 3-D array of 27 random elements using random function of shape 3*3*3. 
Now pull the following elements using indexing/slicing
• Third column of second 2-D array
• First and third row of first 2-D array
• Intersection of first row and third column in third 2-D aray

In [2]:
arr4=np.random.rand(3,3,3)
print(arr4)

[[[0.54839947 0.13022637 0.37767669]
  [0.12545652 0.06677086 0.11653543]
  [0.81540591 0.7413276  0.97611899]]

 [[0.14405727 0.86916543 0.00590173]
  [0.43268543 0.49654154 0.00214605]
  [0.0541897  0.07450993 0.564354  ]]

 [[0.11137316 0.33091469 0.83269406]
  [0.09450545 0.51053917 0.35908292]
  [0.13675906 0.43546633 0.52607882]]]


In [3]:
arr4[1,:,2]

array([0.00590173, 0.00214605, 0.564354  ])

In [ ]:
arr4[0,[0,2]]

In [ ]:
arr4[2,0,2]

Q4. Create a 2-D numpy array of random integers between 1 to 100 with shape 5*4. Now perform following operations:
• Print only the even numbers from this array
• Print only the odd numbers from this array
• Print row wise sum of all elements
• Print column wise sum of all elements
• Convert this 2-D array into 3-D array of shape 2*2*5

In [ ]:
arr5=np.random.randint(1,101,(5,4))

In [ ]:
print(arr5)

In [ ]:
arr5[arr5%2==0]

In [ ]:
arr5[arr5%2!=0]

In [ ]:
arr5.sum(axis=1)

In [ ]:
arr5.sum(axis=0)

In [ ]:
arr5.reshape((2,2,5))

Q5. Create a 2-D numpy array of random integers between 1 to 100 with shape 5*4. Now perform following operations:
• Swap first row with third row
• Swap second column with fourth column.
• Replace the values less than 50 with zero.
• Convert this 2D array into 1-D array

In [ ]:
arr6=np.random.randint(1,101,(5,4))

In [ ]:
print(arr6)

In [ ]:
arr6[[0,2]]=arr6[[2,0]]
print(arr6)

In [ ]:
arr6[:,[1,3]]=arr6[:,[3,1]]
print(arr6)

In [ ]:
arr6[arr6<50]=0
print(arr6)

In [ ]:
arr6.flatten()

Q6. Explain the concept of stacking in numpy with examples.
How is it different from concatenation. Give any 3 differences between them.

### Stacking in Numpy
Stacking is a method of joining multiple arrays along a new axis. The arrays must have the same shape along the non-stacking axes. The stacking operation effectively increases the dimensionality of the resulting array.

1. np.vstack() (Vertical Stacking): Stacks arrays vertically (row-wise). The arrays must have the same number of columns.
2. np.hstack() (Horizontal Stacking): Stacks arrays horizontally (column-wise). The arrays must have the same number of rows.
3. np.dstack() (Depth Stacking): Stacks arrays along the third axis (depth). This is useful for creating 3D arrays from 2D arrays. The arrays must have the same shape.


#### Differences between Stacking and Concatenation
Concatenation is a more general operation that joins arrays along an existing axis. It's performed using the np.concatenate() function. The main difference lies in how they combine arrays and the resulting array's shape.

Here are three key differences between stacking vs concatenation:

Axis of Joining : Joins arrays along a new axis. It increases the dimensionality of the resulting array vs Joins arrays along an existing axis. It maintains the original dimensionality.

Array Shapes : Requires arrays to have the same shape along the non-stacking axes. For vstack, the number of columns must be the same. For hstack, the number of rows must be the same vs Requires arrays to have the same shape along all axes except the one being concatenated.

Functionality : Specialized functions for specific stacking directions: vstack (vertical), hstack (horizontal), dstack (depth) vs A single, general-purpose function (np.concatenate) that requires an axis argument to specify the joining direction.


